//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsSqlServerDatabaseTablesGraph.WebApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsSqlServerDatabaseTablesGraph.WebApp.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование карточки компании.
        /// </summary>
        public static string COMPANY_CARD_EDITING_HEADER {
            get {
                return ResourceManager.GetString("COMPANY_CARD_EDITING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензии компании.
        /// </summary>
        public static string COMPANY_LICENCES {
            get {
                return ResourceManager.GetString("COMPANY_LICENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный сайт работает с Internet Explorer 11 и более новыми версиями..
        /// </summary>
        public static string IE_LESS_11_CAPTION {
            get {
                return ResourceManager.GetString("IE_LESS_11_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудиторы.
        /// </summary>
        public static string LIST_AUDITORS {
            get {
                return ResourceManager.GetString("LIST_AUDITORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Банки и страховые компании.
        /// </summary>
        public static string LIST_BANKS_AND_INSURERS {
            get {
                return ResourceManager.GetString("LIST_BANKS_AND_INSURERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эмитенты.
        /// </summary>
        public static string LIST_ISSUERS {
            get {
                return ResourceManager.GetString("LIST_ISSUERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Типы лицензий.
        /// </summary>
        public static string LIST_LICENCE_TYPES {
            get {
                return ResourceManager.GetString("LIST_LICENCE_TYPES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Периоды.
        /// </summary>
        public static string LIST_PERIODS {
            get {
                return ResourceManager.GetString("LIST_PERIODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регионы.
        /// </summary>
        public static string LIST_REGIONS {
            get {
                return ResourceManager.GetString("LIST_REGIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филиалы.
        /// </summary>
        public static string LIST_REGISTRAR_BRANCHES {
            get {
                return ResourceManager.GetString("LIST_REGISTRAR_BRANCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистраторы.
        /// </summary>
        public static string LIST_REGISTRARS {
            get {
                return ResourceManager.GetString("LIST_REGISTRARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реестры.
        /// </summary>
        public static string LIST_REGISTRIES {
            get {
                return ResourceManager.GetString("LIST_REGISTRIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочники.
        /// </summary>
        public static string LISTS {
            get {
                return ResourceManager.GetString("LISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms Sql Server database tables graph.
        /// </summary>
        public static string LOGO_HEADER {
            get {
                return ResourceManager.GetString("LOGO_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный сайт требует включенной поддержки JavaScript в вашем браузере..
        /// </summary>
        public static string NO_SCRIPT_CAPTION {
            get {
                return ResourceManager.GetString("NO_SCRIPT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание деятельности.
        /// </summary>
        public static string PARTITION_ACTIVITY_DESCRIPTION {
            get {
                return ResourceManager.GetString("PARTITION_ACTIVITY_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string PARTITION_ALL {
            get {
                return ResourceManager.GetString("PARTITION_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аудитор.
        /// </summary>
        public static string PARTITION_AUDITOR {
            get {
                return ResourceManager.GetString("PARTITION_AUDITOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Облигации.
        /// </summary>
        public static string PARTITION_BONDS {
            get {
                return ResourceManager.GetString("PARTITION_BONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Филиалы.
        /// </summary>
        public static string PARTITION_BRANCHES {
            get {
                return ResourceManager.GetString("PARTITION_BRANCHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Карточка компании.
        /// </summary>
        public static string PARTITION_CARD_INFO {
            get {
                return ResourceManager.GetString("PARTITION_CARD_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая информация.
        /// </summary>
        public static string PARTITION_COMMON_INFO {
            get {
                return ResourceManager.GetString("PARTITION_COMMON_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Деятельность компании.
        /// </summary>
        public static string PARTITION_COMPANY_ACTIVITY {
            get {
                return ResourceManager.GetString("PARTITION_COMPANY_ACTIVITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Структура компании.
        /// </summary>
        public static string PARTITION_COMPANY_STRUCTURE {
            get {
                return ResourceManager.GetString("PARTITION_COMPANY_STRUCTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Органы управления.
        /// </summary>
        public static string PARTITION_CONTROLS_ORGANS {
            get {
                return ResourceManager.GetString("PARTITION_CONTROLS_ORGANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Совладельцы.
        /// </summary>
        public static string PARTITION_COOWNERS {
            get {
                return ResourceManager.GetString("PARTITION_COOWNERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Совет директоров.
        /// </summary>
        public static string PARTITION_DIRECTORS {
            get {
                return ResourceManager.GetString("PARTITION_DIRECTORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дивиденды.
        /// </summary>
        public static string PARTITION_DIVIDENDS {
            get {
                return ResourceManager.GetString("PARTITION_DIVIDENDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕГРЮЛ.
        /// </summary>
        public static string PARTITION_ERGUL {
            get {
                return ResourceManager.GetString("PARTITION_ERGUL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнительный орган.
        /// </summary>
        public static string PARTITION_EXECUTIVEOFFICE {
            get {
                return ResourceManager.GetString("PARTITION_EXECUTIVEOFFICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты ФСФР.
        /// </summary>
        public static string PARTITION_FFMS_REPORTS {
            get {
                return ResourceManager.GetString("PARTITION_FFMS_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бухгалтерская отчетность.
        /// </summary>
        public static string PARTITION_FINANCIAL_STATEMENTS {
            get {
                return ResourceManager.GetString("PARTITION_FINANCIAL_STATEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчеты МСФО.
        /// </summary>
        public static string PARTITION_IFRS_REPORTING {
            get {
                return ResourceManager.GetString("PARTITION_IFRS_REPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обязательства.
        /// </summary>
        public static string PARTITION_LIABILITY {
            get {
                return ResourceManager.GetString("PARTITION_LIABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лицензии.
        /// </summary>
        public static string PARTITION_LICENCES {
            get {
                return ResourceManager.GetString("PARTITION_LICENCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Планы.
        /// </summary>
        public static string PARTITION_PLAN {
            get {
                return ResourceManager.GetString("PARTITION_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационные данные.
        /// </summary>
        public static string PARTITION_REG_INFO {
            get {
                return ResourceManager.GetString("PARTITION_REG_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистратор.
        /// </summary>
        public static string PARTITION_REGISTRAR {
            get {
                return ResourceManager.GetString("PARTITION_REGISTRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to РОССТАТ.
        /// </summary>
        public static string PARTITION_ROSSTAT {
            get {
                return ResourceManager.GetString("PARTITION_ROSSTAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ценные бумаги.
        /// </summary>
        public static string PARTITION_SECURITIES {
            get {
                return ResourceManager.GetString("PARTITION_SECURITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акции.
        /// </summary>
        public static string PARTITION_STOCKS {
            get {
                return ResourceManager.GetString("PARTITION_STOCKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дочерние компании.
        /// </summary>
        public static string PARTITION_SUBSIDIARIES {
            get {
                return ResourceManager.GetString("PARTITION_SUBSIDIARIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string REFRESH_CAPTION {
            get {
                return ResourceManager.GetString("REFRESH_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить данные.
        /// </summary>
        public static string REFRESH_CAPTION_TOOLTIP {
            get {
                return ResourceManager.GetString("REFRESH_CAPTION_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string SAVE_CAPTION {
            get {
                return ResourceManager.GetString("SAVE_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить данные.
        /// </summary>
        public static string SAVE_CAPTION_TOOLTIP {
            get {
                return ResourceManager.GetString("SAVE_CAPTION_TOOLTIP", resourceCulture);
            }
        }
    }
}
